application: candersonmiller1984
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py
- url: /post
  script: main.py
- url: /recieve
  script: main.py
- url: /img
  script: image.py
- url: /edit
  script: main.py
- url: /recieveedit
  script: main.py
- url: /rss
  script: rss.py
- url: /settings
  script: settings.py
- url: /settingssubmit
  script: settings.py
- url: /postedit
  script: postedit.py
- url: /publish
  script: publish.py
- url: /unpublish
  script: publish.py
- url: /rendered
  script: rendered.py
- url: /test
  script: test.py
- url: /fullimage
  script: image.py
- url: /thumbnail
  script: image.py
- url: /postimage
  script: image.py
- url: /sortimage.*
  script: image.py
- url: /updatedimages.*
  script: image.py
- url: /phonepost
  script: image.py
- url: /
  static_dir: assets
